ktor:
  application:
    id: nginx-sidewheel
    modules:
      - br.com.dillmann.nginxsidewheel.application.ApplicationKt.module
  deployment:
    port: 8080

nginx-sidewheel:
  nginx:
    binary-path: nginx
    config-directory: /tmp/nginx-sidewheel/config
  database:
    url: "jdbc:h2:mem:nginx-sidewheel;DB_CLOSE_DELAY=-1"
    username: root
    password: root
  security:
    user-password-hashing:
      algorithm: SHA-512
      salt-size: 64
      iterations: 1024
