name: release-pipeline
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Gradle cache
        uses: actions/cache@v4
        with:
          path: ~/.gradle
          key: gradle-cache
          restore-keys: gradle-cache
      - name: npm cache
        uses: actions/cache@v4
        with:
          path: ~/frontend/node_modules
          key: npm-cache
          restore-keys: npm-cache
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          driver-opts: |
            image=moby/buildkit:master
            network=host
          platforms: linux/amd64,linux/arm64
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: tag
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - run: |
          ./gradlew assemble && \
          docker buildx \
            --tag dillmann/nginx-ignition:${{ steps.tag.outputs.VERSION }} \
            --platform linux/amd64,linux/arm64 \
            --builder docker-container \
            --push .

